### ISSUE TITLE
Missing release for 2020.2

### ISSUE THREAD

**Issue by dziemich** [Madrapps/dagger-plugin#27]
Can this plugin be released for the new IDEA version?

**Comment by thsaravana** [comment]
Supported in cf747f2e45216134f6a02ce151a728822a0d441a
For some reason, I am unable to upload the binary to JetBrains. Keep getting Internal Error. I have written to them about this issue, and waiting to hear from them.

**Comment by thsaravana** [comment]
Finally, update for 2020.2 is available.
