### ISSUE TITLE
Update Dagger plugin to support Intellij IDEA 2021.1

### ISSUE THREAD

**Issue by sunyang713** [Madrapps/dagger-plugin#33]
Got the following error when I updated Intellij:

>Plugin 'Dagger' (version '0.3.2020.3.3') is not compatible with the current version of the IDE, because it requires build 203.* or older but the current build is IU-211.6693.111

**Comment by thsaravana** [comment]
Thanks @sunyang713 . Uploaded the build to Marketplace. Version 0.3.2021.1.1 should be available in a couple of days.
