### ISSUE TITLE
Plugin freezes Android Studio completely while running task "Analysing dagger dependencies"

### ISSUE THREAD

**Issue by promikhail** [Madrapps/dagger-plugin#37]
Plugin freezes Android Studio completely while running task "Analysing dagger dependencies".
If disable/uninstall this plugin Android Studio working normally
Android Studio version 4.2.2

**Comment by thsaravana** [comment]
Hi @promikhail, could you let me know what version of Gradle and dagger you are using in your project? Also, could you give a picture of how big your project dependencies are, to know if that could be an issue.
