### ISSUE TITLE
Support for Android Studio Artic Fox

### ISSUE THREAD

**Issue by Jacob3075** [Madrapps/dagger-plugin#41]
Cannot install plugin in Android Studio Artic Fox

**Comment by thsaravana** [comment]
It should support Artic fox. Do you not see the plugin in the marketplace? Or while installing are you facing any specific issues? I just tested in Android studio Bumblebee 2021.1.1 and it works as expected.

**Comment by Jacob3075** [comment]
I am not using android anymore and I do not remember why exactly it was not working, I think it said that it is not compatible with the current version of the IDE. If it is working now for you then you can close it I guess.
