### ISSUE TITLE
Add support for 2021.3.x

### ISSUE THREAD

**Issue by CC007** [Madrapps/dagger-plugin#42]
Title is self-explanatory

**Comment by CC007** [comment]
Maybe you could also prepare the plugin for the EAP version, so that it takes less effort to switch over once the EAP becomes the latest release.

**Comment by CC007** [comment]
Updated the title, because 2021.3.1 is now also released.

**Comment by thsaravana** [comment]
Sorry. Was away for a while. Uploaded to marketplace and should be available in couple of days. I will be uploading another for the EAP as well.
